### ISSUE TITLE
웹로직(weblogic) 12.1.3 + AXU , axu4j 에러문의

### ISSUE THREAD

**Issue by slowk** [axisj/axisj#935]
Tomcat과 구동시에는 잘됩니다만...

웹로직을 콘솔을 통해 서버 구동을 시키고 프로젝트를 war로 묶어 서버에 올리면 
일반 로직의 페이지는 잘 구동이 되나

AXU와 엑시스제이로 구성된 페이지에서는 아래와 같은 에러가 발생합니다. 
해결 방법에 대해 알수 있을까요?? 

[Error] [com.axisj.axu4j.config.ConfigReader] [WIN-2HG1V33LJ5C] [myserver] [[ACTIVE] ExecuteThread: '3' for queue: 'weblogic.kernel.Default (self-tuning)'] [[anonymous]] [] [] [1474527889501] [BEA-000000] [Fail to load axu4j.xml
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.[init](File.java:418)
	at com.axisj.axu4j.config.ConfigReader.load(ConfigReader.java:61)
	at com.axisj.axu4j.config.ConfigReader.load(ConfigReader.java:79)
	at com.axisj.axu4j.config.ConfigReader.getConfig(ConfigReader.java:30)
	at com.axisj.axu4j.tags.RowTag.beforeDoTag(RowTag.java:49)
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:80)
	at jsp_servlet.__index._jsp__tag7(__index.java:332)
	at jsp_servlet.__index.access$19(__index.java:315)
	at jsp_servlet.__index$JspFragmentHelper.invoke3(__index.java:500)
	at jsp_servlet.__index$JspFragmentHelper.invoke(__index.java:557)
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44)
	at com.axisj.axu4j.tags.DivTag.doTag(DivTag.java:31)
	at jsp_servlet.__index._jsp__tag6(__index.java:310)
	at jsp_servlet.__index.access$9(__index.java:292)
	at jsp_servlet.__index$JspFragmentHelper.invoke0(__index.java:480)
	at jsp_servlet.__index$JspFragmentHelper.invoke(__index.java:548)
	at com.axisj.axu4j.tags.LayoutTag.doTag(LayoutTag.java:57)
	at jsp_servlet.__index._jsp__tag0(__index.java:171)
	at jsp_servlet.__index._jspService(__index.java:140)
	at weblogic.servlet.jsp.JspBase.service(JspBase.java:35)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
	at weblogic.servlet.internal.ServletStubImpl.onAddToMapException(ServletStubImpl.java:483)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:372)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:243)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3432)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3402)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2285)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2201)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1572)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:255)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
] 

[Error] [com.axisj.axu4j.tags.CustomTag] [WIN-2HG1V33LJ5C] [myserver] [[ACTIVE] ExecuteThread: '3' for queue: 'weblogic.kernel.Default (self-tuning)'] [[anonymous]] [] [] [1474527889511] [BEA-000000] [doTag is fail.
tagBody: 
mustacheHtml: null
java.lang.RuntimeException: 사용가능한 custom tag 설정이 없습니다.
axu4j.xml 설정파일에서 [customs] 내용을 확인하세요.
	at com.axisj.axu4j.tags.CustomTag.beforeDoTag(CustomTag.java:41)
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:80)
	at jsp_servlet.__index._jsp__tag9(__index.java:379)
	at jsp_servlet.__index.access$36(__index.java:360)
	at jsp_servlet.__index$JspFragmentHelper.invoke5(__index.java:526)
	at jsp_servlet.__index$JspFragmentHelper.invoke(__index.java:563)
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44)
	at com.axisj.axu4j.tags.ColTag.beforeDoTag(ColTag.java:65)
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:80)
	at jsp_servlet.__index._jsp__tag8(__index.java:355)
	at jsp_servlet.__index.access$22(__index.java:337)
	at jsp_servlet.__index$JspFragmentHelper.invoke4(__index.java:508)
	at jsp_servlet.__index$JspFragmentHelper.invoke(__index.java:560)
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44)
	at com.axisj.axu4j.tags.RowTag.beforeDoTag(RowTag.java:50)
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:80)
	at jsp_servlet.__index._jsp__tag7(__index.java:332)
	at jsp_servlet.__index.access$19(__index.java:315)
	at jsp_servlet.__index$JspFragmentHelper.invoke3(__index.java:500)
	at jsp_servlet.__index$JspFragmentHelper.invoke(__index.java:557)
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44)
	at com.axisj.axu4j.tags.DivTag.doTag(DivTag.java:31)
	at jsp_servlet.__index._jsp__tag6(__index.java:310)
	at jsp_servlet.__index.access$9(__index.java:292)
	at jsp_servlet.__index$JspFragmentHelper.invoke0(__index.java:480)
	at jsp_servlet.__index$JspFragmentHelper.invoke(__index.java:548)
	at com.axisj.axu4j.tags.LayoutTag.doTag(LayoutTag.java:57)
	at jsp_servlet.__index._jsp__tag0(__index.java:171)
	at jsp_servlet.__index._jspService(__index.java:140)
	at weblogic.servlet.jsp.JspBase.service(JspBase.java:35)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
	at weblogic.servlet.internal.ServletStubImpl.onAddToMapException(ServletStubImpl.java:483)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:372)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:243)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3432)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3402)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2285)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2201)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1572)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:255)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
]

**Comment by hyunjun19** [comment]
웹로직에서 테스트를 해봐야 알것 같습니다...
혹시 톰캣과 같은 OS에서 테스트해 보신건가요?

**Comment by slowk** [comment]
네 동일하게 windows에서 구동하여 진행했습니다.
이클립스를 통해 소스를 war로 export하고 
콘솔을 통해 웹로직을 start하여 배치에 해당 war를 배포하여 테스트 하면 위와같은 증상이 나타납니다.
조언 부탁드려요

**Comment by hyunjun19** [comment]
빠른 시일내에 웹로직에서 테스트를 해보도록 하겠습니다.

추가로 한 가지 더~
war로 export한 파일안에 `axu4j.xml`이 잘 들어가 있나요?
war로 묶으면서 XML이 제외될 수도 있기 때문에 이 부분을 확인해 보세요.

**Comment by hyunjun19** [comment]
https://github.com/axisj/axu4j/issues/37 이 문제와 동일한 문제로 보여집니다.
일단 여기는 axisj 이슈이기 때문에 종료하고 axu4j 이슈를 참고해주세요.
